### ISSUE TITLE
Domain expired?

### ISSUE THREAD

**Issue by leilatite** [stpaultim/MyFavoriteMeetingPlace#39]
I had some time this morning to review locations on the site, but I get an expired domain page for http://myfavoritemeetingplace.com/

**Comment by stpaultim** [comment]
Darn! My fault. It was working yesterday. I will try to fix it today. Tim---- On Fri, 10 Mar 2017 05:50:42 -0800  Leila Tite<notifications@github.com> wrote ----I had some time this morning to review locations on the site, but I get an expired domain page for http://myfavoritemeetingplace.com/  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by stpaultim** [comment]
It's been one year since we set up the site and registered the domain. It was aware that it was expiring this week, but I did not get around to renewing. 

I just renewed it now. It should take effect shortly.
